In [1]:
import pymysql

In [4]:
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='mysql')

In [6]:
cursor=connection.cursor()

In [7]:
### database of hospital
query= "create database hospital"

cursor.execute(query)
connection.commit()

In [8]:
### create tables in hospital db

query= """ use hospital;
create table doctors (
doctor_id int PRIMARY KEY,
  first_name varchar(50),
  last_name varchar(50),
  specialty varchar(50),
  phone_number varchar(50),
  email varchar(50)

);

create table patients(
  patient_id int PRIMARY KEY,
  first_name varchar(50),
  last_name varchar(50),
  gender char,
  date_of_birth DATE,
  phone_number VARCHAR(50),
  city VARCHAR(50),
  email VARCHAR(50)

);

create table Appointments(
appointment_id INT PRIMARY KEY,
  patient_id int,
  doctor_id int,
  appointment_date DATE,
  appointment_time TIME,
  reason VARCHAR(100),
  status VARCHAR(50));

create table Treatments(
treatment_id varchar(255) PRIMARY KEY,
  appointment_id INT,
  diagnosis VARCHAR(100),
  treatment_details VARCHAR(100),
  prescription VARCHAR(100),
  treatment_date DATE);


create table Billing (
  billing_id INT PRIMARY KEY,
  treatment_id varchar(255),
  amount DECIMAL(10,5),
  payment_status VARCHAR(50),
  billing_date DATE);

ALTER TABLE Billing ADD FOREIGN KEY (treatment_id) REFERENCES Treatments (treatment_id);

ALTER TABLE Treatments ADD FOREIGN KEY (appointment_id) REFERENCES Appointments (appointment_id);

ALTER TABLE Appointments ADD FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id);

ALTER TABLE Appointments ADD FOREIGN KEY (patient_id) REFERENCES patients (patient_id);"""

In [9]:
for statement in query.split(";"):
    if statement.strip():
        cursor.execute(statement)
connection.commit()

In [10]:
### csv data read and insert into table

In [12]:
import pandas as pd 
from sqlalchemy import create_engine

In [13]:
engine= create_engine("mysql+pymysql://root:mysql@localhost/hospital")

In [14]:
doctor= pd.read_csv(r"C:\Users\prash\Downloads\Hospital_management\doctors.csv")

In [15]:
patient=pd.read_csv(r"C:\Users\prash\Downloads\Hospital_management\patients.csv")

In [33]:
patient.head()

,patient_id,first_name,last_name,gender,date_of_birth,phone_number,city,email
0,1,Benjamin,Glass,F,1/23/1997,9943341901,Delhi,johnmoore@gmail.com
1,2,Jeffery,Mccoy,F,8/21/2014,9291552695,Kolkata,williamharper@hotmail.com
2,3,Stacy,Young,M,12/4/2015,9276841607,Bangalore,baileymatthew@jones.com
3,4,Samuel,Sutton,M,5/9/2011,9644221514,Chandighar,mhernandez@rosario.com
4,5,David,Williams,F,4/24/1972,9996410097,Pune,susan30@pierce-davis.info

In [34]:
patient['date_of_birth']=pd.to_datetime(patient['date_of_birth']).dt.strftime('%Y-%m-%d')

In [35]:
patient.head()

,patient_id,first_name,last_name,gender,date_of_birth,phone_number,city,email
0,1,Benjamin,Glass,F,1997-01-23,9943341901,Delhi,johnmoore@gmail.com
1,2,Jeffery,Mccoy,F,2014-08-21,9291552695,Kolkata,williamharper@hotmail.com
2,3,Stacy,Young,M,2015-12-04,9276841607,Bangalore,baileymatthew@jones.com
3,4,Samuel,Sutton,M,2011-05-09,9644221514,Chandighar,mhernandez@rosario.com
4,5,David,Williams,F,1972-04-24,9996410097,Pune,susan30@pierce-davis.info

In [17]:
appoitment= pd.read_csv(r"C:\Users\prash\Downloads\Hospital_management\appointments.csv")

In [18]:
appointment.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason,status
0,1,165,18,6/23/2024,7:40:54,Follow-up,Completed
1,2,200,16,1/30/2024,21:49:53,Emergency Visit,Scheduled
2,3,317,20,9/30/2024,14:40:15,Follow-up,Completed
3,4,189,4,1/20/2024,9:57:59,Emergency Visit,Scheduled
4,5,61,3,12/17/2024,16:43:14,Follow-up,Scheduled

In [19]:
appointment['appointment_date']=pd.to_datetime(appointment['appointment_date']).dt.strftime('%Y-%m-%d')

In [21]:
appointment.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason,status
0,1,165,18,2024-06-23,7:40:54,Follow-up,Completed
1,2,200,16,2024-01-30,21:49:53,Emergency Visit,Scheduled
2,3,317,20,2024-09-30,14:40:15,Follow-up,Completed
3,4,189,4,2024-01-20,9:57:59,Emergency Visit,Scheduled
4,5,61,3,2024-12-17,16:43:14,Follow-up,Scheduled

In [22]:
treatment=pd.read_csv(r"C:\Users\prash\Downloads\Hospital_management\treatments.csv")

In [23]:
treatment.head()

,treatment_id,appointment_id,diagnosis,treatment_details,prescription,treatment_date
0,TRID1,1,Diabetes,Head wear strategy art candidate. Method conce...,Street effect debate available.,11/19/2024
1,TRID2,2,Muscle Strain,Attorney scientist eat want hundred amount rea...,Even thus change.,12/23/2024
2,TRID3,3,Angina,Special energy strong question than among check.,Situation line one box can reach herself.,4/8/2024
3,TRID4,4,Hypertension,Possible company process answer similar star t...,Catch table base thousand.,11/2/2024
4,TRID5,5,Angina,Why number five each less lead try. Do accordi...,Suffer sister force hour maybe instead.,4/1/2024

In [24]:
treatment['treatment_date']=pd.to_datetime(treatment['treatment_date']).dt.strftime('%Y-%m-%d')

In [25]:
treatment.head()

,treatment_id,appointment_id,diagnosis,treatment_details,prescription,treatment_date
0,TRID1,1,Diabetes,Head wear strategy art candidate. Method conce...,Street effect debate available.,2024-11-19
1,TRID2,2,Muscle Strain,Attorney scientist eat want hundred amount rea...,Even thus change.,2024-12-23
2,TRID3,3,Angina,Special energy strong question than among check.,Situation line one box can reach herself.,2024-04-08
3,TRID4,4,Hypertension,Possible company process answer similar star t...,Catch table base thousand.,2024-11-02
4,TRID5,5,Angina,Why number five each less lead try. Do accordi...,Suffer sister force hour maybe instead.,2024-04-01

In [26]:
billing=pd.read_csv(r"C:\Users\prash\Downloads\Hospital_management\billing.csv")

In [27]:
billing.head()

   billing_id treatment_id  amount payment_status billing_date
0           1        TRID1  430.05         Unpaid    3/11/2024
1           2        TRID2  817.96         Unpaid     8/8/2024
2           3        TRID3  713.88         Unpaid   10/17/2024
3           4        TRID4  866.38         Unpaid     7/3/2024
4           5        TRID5  898.36           Paid    10/9/2024

In [28]:
billing['billing_date']=pd.to_datetime(billing['billing_date']).dt.strftime('%Y-%m-%d')

In [29]:
billing.head()

   billing_id treatment_id  amount payment_status billing_date
0           1        TRID1  430.05         Unpaid   2024-03-11
1           2        TRID2  817.96         Unpaid   2024-08-08
2           3        TRID3  713.88         Unpaid   2024-10-17
3           4        TRID4  866.38         Unpaid   2024-07-03
4           5        TRID5  898.36           Paid   2024-10-09

In [30]:
doctor.to_sql('doctors',con=engine,if_exists='append',index=False)

20

In [36]:
patient.to_sql('patients',con=engine,if_exists='append',index=False)

500

In [37]:
appointment.to_sql('Appointments',con=engine,if_exists='append',index=False)

C:\Users\prash\AppData\Local\Temp\ipykernel_29920\2854110150.py:1: UserWarning: The provided table name 'Appointments' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  appointment.to_sql('Appointments',con=engine,if_exists='append',index=False)

500

In [38]:
treatment.to_sql('Treatments',con=engine,if_exists='append',index=False)

C:\Users\prash\AppData\Local\Temp\ipykernel_29920\817709253.py:1: UserWarning: The provided table name 'Treatments' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  treatment.to_sql('Treatments',con=engine,if_exists='append',index=False)

500

In [39]:
billing.to_sql('Billing',con=engine,if_exists='append',index=False)

C:\Users\prash\AppData\Local\Temp\ipykernel_29920\1296224387.py:1: UserWarning: The provided table name 'Billing' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  billing.to_sql('Billing',con=engine,if_exists='append',index=False)

500